/********************************************************************
**       This cc file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: person.proto

#include "person.msg.h"

bool CDMDispatcher_db::Init()
{

    Register(::db::MSGID::MSGID_tb_Person, &CDMDispatcher_db::Ontb_Person, sizeof(::db::tb_Person));
    return true;
}

int CDMDispatcher_db::NetCall(uint16_t wMsgID, void* pData, int nLen, const void* pObject = NULL)
{
    ::google::protobuf::Message* poMsg = CreateMessage(wMsgID);
    if (NULL == poMsg)
    {
        return GetErrorNG();
    }

    if (!poMsg->ParseFromArray(pData, nLen))
    {
        ReleaseMessage(poMsg);
        return GetErrorNG();
    }
    int nResult = MGCall(wMsgID, *poMsg, poMsg->ByteSize(), pObject);
    ReleaseMessage(poMsg);
    return nResult;
}

::google::protobuf::Message* CDMDispatcher_db::CreateMessage(uint16_t wMsgID)
{
    switch(wMsgID)
    {
       
    case ::db::MSGID::MSGID_tb_Person:
        {
            return new ::db::tb_Person;
        }
        break;

    default:
        assert(0);
        return NULL;
    }
}

void CDMDispatcher_db::ReleaseMessage(::google::protobuf::Message* poMsg)
{
    delete poMsg;
}

int CDMDispatcher_db::Ontb_Person(::google::protobuf::Message& msg, int nLen, const void* pObject)
{
    ::db::tb_Person* pData = dynamic_cast<::db::tb_Person*>(&msg);
    return 0;
}
